# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-23 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstdbtest', '0002_auto_20210223_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_dob',
            field=models.DateField(),
        ),
    ]
