# Generated by Django 3.1.5 on 2021-03-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('catageory', models.CharField(max_length=10)),
                ('subcatageory', models.CharField(max_length=10)),
                ('photo', models.ImageField(upload_to='static/img')),
                ('quentity', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=10)),
                ('longDescription', models.CharField(max_length=1000)),
            ],
        ),
    ]
